"use client";

import Image from "next/image";
import { useState } from "react";
import { ArrowRight, Check, MapPin, MessageCircle, Send, ShieldCheck, Star, WalletCards, Workflow } from "lucide-react";
import { Accordion } from "@/components/ui/accordion";
import { Button, ButtonLink } from "@/components/ui/button";
import { GlassCard } from "@/components/ui/glass-card";
import { Reveal, HoverLift, Parallax } from "@/components/motion";
import { benefits, courses, gallery, heroImage, nav, reviews, teachers, timeline } from "@/components/data";
import { ReviewSlider } from "@/components/review-slider";

/** Complete landing page for the premium practical massage school. */
export function MassageSchoolSite() {
  const [sent, setSent] = useState(false);
  return (
    <>
      <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[60] focus:rounded-full focus:bg-[#0f3328] focus:px-5 focus:py-3 focus:text-white">Перейти к содержимому</a>
      <header className="fixed inset-x-0 top-4 z-50 mx-auto w-[min(1180px,calc(100%-24px))] rounded-full border border-white/50 bg-white/55 px-4 py-3 shadow-2xl shadow-black/5 backdrop-blur-[30px] dark:border-white/10 dark:bg-black/30">
        <nav className="flex items-center justify-between gap-5" aria-label="Главная навигация">
          <a href="#top" className="flex items-center gap-3 font-black"><span className="grid size-10 place-items-center rounded-full bg-[#0f3328] text-[#c7a45b]">M</span> Maison Massage</a>
          <div className="hidden gap-5 text-sm font-semibold text-[var(--muted)] lg:flex">{nav.map((n) => <a key={n} href={`#${slug(n)}`} className="transition hover:text-[#0f3328] dark:hover:text-[#c7a45b]">{n}</a>)}</div>
          <ButtonLink href="#запись" className="min-h-10 px-4">Записаться</ButtonLink>
        </nav>
      </header>
      <main id="main-content" className="overflow-hidden">
        <section id="top" className="relative min-h-screen px-4 pb-16 pt-28 sm:px-6 lg:px-8">
          <Parallax className="absolute inset-0 -z-10"><Image src={heroImage} alt="Массажист проводит практическое занятие" fill priority sizes="100vw" className="object-cover opacity-75 dark:opacity-45" /></Parallax>
          <div className="absolute inset-0 -z-10 bg-gradient-to-b from-white/15 via-[#f8f8f7]/75 to-[#f8f8f7] dark:from-black/10 dark:via-black/65 dark:to-[#070908]" />
          <div className="mx-auto grid min-h-[78vh] max-w-7xl items-end gap-8 lg:grid-cols-[1.15fr_.85fr]">
            <Reveal><GlassCard className="p-7 sm:p-10 lg:p-14"><p className="mb-4 text-sm font-black uppercase tracking-[.24em] text-[#c7a45b]">Практическая школа массажа</p><h1 className="max-w-4xl text-5xl font-black leading-[.92] tracking-[-.06em] sm:text-7xl lg:text-8xl">Профессиональные курсы массажа с практикой</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">Освой востребованную профессию за несколько недель. Более 80% обучения — практика на реальных моделях. Получите сертификат и начните карьеру массажиста уже после окончания курса.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="#запись">Записаться <ArrowRight className="size-4" /></ButtonLink><ButtonLink href="#программа-обучения" variant="ghost">Смотреть программу</ButtonLink></div></GlassCard></Reveal>
            <Reveal delay={.15}><GlassCard className="grid gap-5 p-7"><div className="grid grid-cols-3 gap-3 text-center"><Stat value="12" label="лет школы"/><Stat value="2400+" label="выпускников"/><Stat value="80%" label="практики"/></div><p className="text-[var(--muted)]">Камерные группы, реальные модели, наставничество и готовые сценарии запуска частной практики.</p></GlassCard></Reveal>
          </div>
        </section>
        <Section id="преимущества" title="Почему выбирают нас" subtitle="Каждая деталь обучения построена вокруг уверенной практики, безопасности и премиального клиентского сервиса.">
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon, title, text], i) => <Reveal key={title as string} delay={i*.04}><HoverLift><GlassCard className="h-full"><Icon className="mb-8 size-8 text-[#c7a45b]"/><h3 className="text-xl font-black">{title as string}</h3><p className="mt-3 text-[var(--muted)]">{text as string}</p></GlassCard></HoverLift></Reveal>)}</div>
        </Section>
        <Section id="о-школе" title="Школа, где руки начинают думать" subtitle="Мы выросли из частной студии практиков и за 12 лет превратились в образовательное пространство с сильной методикой, эстетикой и уважением к телу.">
          <div className="grid gap-6 lg:grid-cols-2"><Reveal><div className="grid grid-cols-2 gap-4"><ImageCard src={gallery[0]} tall/><ImageCard src={gallery[1]}/><ImageCard src={gallery[2]}/></div></Reveal><Reveal delay={.12}><GlassCard className="h-full p-8 lg:p-10"><h3 className="text-3xl font-black tracking-[-.04em]">Миссия Maison Massage — выпускать специалистов, которым доверяют.</h3><p className="mt-5 text-lg leading-8 text-[var(--muted)]">Мы соединяем анатомию, постановку рук, психологию сервиса и практику на реальных моделях. Ученики проходят путь от базовой теории до экзамена и получают понятный план развития после выпуска.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat value="12" label="лет опыта"/><Stat value="2 400+" label="выпускников"/><Stat value="4.9" label="рейтинг"/></div></GlassCard></Reveal></div>
        </Section>
        <Section id="курсы" title="Курсы" subtitle="Программы подготовлены к подключению CMS: карточки легко заменить реальными данными, ценами и расписанием."><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{courses.map((c, i) => <Reveal key={c[0]} delay={i*.03}><HoverLift><GlassCard className="h-full p-3"><Image src={c[5]} alt={c[0]} width={900} height={620} className="h-64 w-full rounded-[24px] object-cover"/><div className="p-5"><h3 className="text-2xl font-black">{c[0]}</h3><p className="mt-3 text-[var(--muted)]">{c[1]}</p><div className="my-5 grid grid-cols-3 gap-2 text-sm"><Mini label="Длительность" value={c[2]}/><Mini label="Практика" value={c[3]}/><Mini label="Цена" value={c[4]}/></div><Button className="w-full" type="button">Подробнее</Button></div></GlassCard></HoverLift></Reveal>)}</div></Section>
        <Section id="программа-обучения" title="Программа обучения" subtitle="Пошаговый маршрут от понимания тела до уверенной работы с клиентом."><div className="relative mx-auto max-w-4xl before:absolute before:left-5 before:top-0 before:h-full before:w-px before:bg-[#c7a45b]/40 md:before:left-1/2">{timeline.map((t, i) => <Reveal key={t} delay={i*.06}><div className={`relative mb-6 flex ${i%2 ? "md:justify-end" : ""}`}><GlassCard className="ml-12 w-[calc(100%-3rem)] md:ml-0 md:w-[46%]"><span className="absolute -left-10 top-6 grid size-10 place-items-center rounded-full bg-[#0f3328] text-white md:left-[calc(50%-20px)]">{i+1}</span><h3 className="text-2xl font-black">{t}</h3><p className="mt-2 text-[var(--muted)]">Практический модуль с чек-листом навыков, обратной связью и понятным результатом.</p></GlassCard></div></Reveal>)}</div></Section>
        <Section id="практика" title="Практические занятия" subtitle="Более 80% обучения занимает практика под контролем опытных преподавателей."><div className="columns-1 gap-5 sm:columns-2 lg:columns-3">{gallery.map((src, i) => <Reveal key={src} delay={i*.04} className="mb-5 break-inside-avoid"><HoverLift><Image src={src} alt="Практическое занятие по массажу" width={760} height={i%2 ? 900 : 620} className="w-full rounded-[32px] object-cover shadow-2xl shadow-black/10"/></HoverLift></Reveal>)}</div></Section>
        <Section id="преподаватели" title="Преподаватели" subtitle="Наставники с сильной практикой, сертификатами и опытом запуска специалистов."><div className="grid gap-6 md:grid-cols-3">{teachers.map((t) => <GlassCard key={t[0]}><Image src={t[4]} alt={t[0]} width={700} height={760} className="mb-5 h-72 w-full rounded-[24px] object-cover"/><h3 className="text-2xl font-black">{t[0]}</h3><p className="mt-2 text-[#c7a45b]">Опыт: {t[1]}</p><p className="text-[var(--muted)]">{t[2]}. {t[3]}.</p></GlassCard>)}</div></Section>
        <Section id="отзывы" title="Отзывы выпускников" subtitle="Живые истории учеников, которые превратили обучение в новую профессию."><ReviewSlider reviews={reviews} /></Section>
        <Section id="faq" title="FAQ" subtitle="Ответы на главные вопросы перед стартом обучения."><Accordion items={["Нужен ли опыт?","Есть ли сертификат?","Можно ли в рассрочку?","Сколько длится обучение?","Помогаете ли с трудоустройством?","Есть ли практика?","Что нужно взять с собой?"].map(q => ({question:q, answer:"Да. Мы подробно объясняем условия на консультации, помогаем выбрать программу и заранее присылаем список подготовки к занятиям."}))}/></Section>
        <Section id="стоимость" title="Стоимость обучения" subtitle="Три прозрачных формата. Онлайн-оплату можно подключить через подготовленный CTA-поток."><div className="grid gap-6 lg:grid-cols-3">{[["Базовый", ["Теория","Практика","Сертификат"], "39 000 ₽"],["Профессиональный", ["Всё из базового","Дополнительные техники","Поддержка преподавателя","Разбор ошибок"], "59 000 ₽"],["VIP", ["Индивидуальное обучение","Максимум практики","Все техники","Персональный наставник","Помощь в поиске клиентов"], "119 000 ₽"]].map((p, i)=><GlassCard key={p[0] as string} className={i===1 ? "ring-2 ring-[#c7a45b]" : ""}><h3 className="text-3xl font-black">{p[0] as string}</h3><p className="my-5 text-4xl font-black text-[#0f3328] dark:text-[#c7a45b]">{p[2] as string}</p><ul className="space-y-3">{(p[1] as string[]).map(x=><li key={x} className="flex gap-3"><Check className="size-5 text-[#c7a45b]"/> {x}</li>)}</ul><ButtonLink href="#запись" className="mt-8 w-full">Выбрать</ButtonLink></GlassCard>)}</div></Section>
        <Section id="интеграции" title="Готово к масштабированию" subtitle="Архитектура лендинга заранее предусматривает CMS, онлайн-оплату и CRM без изменения пользовательского сценария."><div className="grid gap-6 md:grid-cols-3"><GlassCard><Workflow className="mb-6 size-9 text-[#c7a45b]"/><h3 className="text-2xl font-black">CMS-ready</h3><p className="mt-3 text-[var(--muted)]">Курсы, преподаватели, цены и отзывы вынесены в структурированные данные.</p></GlassCard><GlassCard><WalletCards className="mb-6 size-9 text-[#c7a45b]"/><h3 className="text-2xl font-black">Онлайн-оплата</h3><p className="mt-3 text-[var(--muted)]">CTA и тарифы подготовлены к подключению платежного провайдера.</p></GlassCard><GlassCard><ShieldCheck className="mb-6 size-9 text-[#c7a45b]"/><h3 className="text-2xl font-black">CRM-поток</h3><p className="mt-3 text-[var(--muted)]">Форма собирает нужные поля для передачи заявки в CRM.</p></GlassCard></div></Section>
        <Section id="контакты" title="Контакты" subtitle="Запишитесь на экскурсию по школе или получите консультацию по программе."><div className="grid gap-6 lg:grid-cols-2"><GlassCard><div className="grid min-h-96 place-items-center rounded-[24px] bg-[#0f3328] text-center text-white"><MapPin className="mx-auto mb-4 size-12 text-[#c7a45b]"/><p className="text-2xl font-black">Интерактивная карта</p><p className="text-white/70">Москва, ул. Примерная, 12</p></div></GlassCard><GlassCard className="space-y-4 text-lg"><p>Телефон: +7 900 000-00-00</p><p>WhatsApp: +7 900 000-00-00</p><p>Telegram: @maisonmassage</p><p>Email: hello@maison.example</p><p>Время работы: ежедневно 10:00–21:00</p></GlassCard></div></Section>
        <Section id="запись" title="Форма записи" subtitle="Оставьте заявку — появится анимированное подтверждение, а CRM-интеграцию можно подключить следующим шагом."><GlassCard className="mx-auto max-w-3xl p-8"><form onSubmit={(e)=>{e.preventDefault(); setSent(true);}} className="grid gap-4"><Input label="Имя"/><Input label="Телефон" type="tel"/><Input label="Email" type="email"/><select className="min-h-14 rounded-2xl border border-black/10 bg-white/50 px-4 dark:bg-white/10" aria-label="Выбор курса">{courses.map(c=><option key={c[0]}>{c[0]}</option>)}</select><textarea placeholder="Комментарий" className="min-h-32 rounded-2xl border border-black/10 bg-white/50 p-4 dark:bg-white/10"/><Button type="submit"><Send className="size-4"/> Записаться на курс</Button>{sent && <Reveal><p className="rounded-2xl bg-[#0f3328] p-4 text-center font-bold text-white">Заявка принята. Мы свяжемся с вами в ближайшее время ✨</p></Reveal>}</form></GlassCard></Section>
      </main>
      <footer className="px-4 pb-10"><GlassCard className="mx-auto flex max-w-7xl flex-col justify-between gap-6 p-8 md:flex-row"><div><p className="text-2xl font-black">Maison Massage</p><p className="text-[var(--muted)]">© 2026. Политика конфиденциальности · Пользовательское соглашение</p></div><div className="flex gap-4"><MessageCircle/> <Send/> <Star/></div></GlassCard></footer>
    </>
  );
}
function Section({ id, title, subtitle, children }: { id: string; title: string; subtitle: string; children: React.ReactNode }) { return <section id={id} className="section-pad px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><Reveal><div className="mb-12 max-w-3xl"><p className="mb-3 text-sm font-black uppercase tracking-[.24em] text-[#c7a45b]">{title}</p><h2 className="text-4xl font-black leading-tight tracking-[-.05em] sm:text-6xl">{title}</h2><p className="mt-5 text-lg leading-8 text-[var(--muted)]">{subtitle}</p></div></Reveal>{children}</div></section>; }
function Stat({ value, label }: { value: string; label: string }) { return <div className="rounded-3xl bg-white/35 p-4 dark:bg-white/5"><b className="block text-3xl font-black">{value}</b><span className="text-sm text-[var(--muted)]">{label}</span></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/35 p-3 dark:bg-white/5"><span className="block text-[11px] text-[var(--muted)]">{label}</span><b>{value}</b></div>; }
function ImageCard({ src, tall = false }: { src: string; tall?: boolean }) { return <Image src={src} alt="Фото учебного процесса" width={700} height={900} className={`${tall ? "row-span-2 h-full" : "h-64"} w-full rounded-[32px] object-cover shadow-2xl shadow-black/10`} />; }
function Input({ label, type = "text" }: { label: string; type?: string }) { return <input required type={type} placeholder={label} className="min-h-14 rounded-2xl border border-black/10 bg-white/50 px-4 outline-none transition focus:ring-4 focus:ring-[#c7a45b]/25 dark:bg-white/10" />; }
function slug(value: string) { return value.toLowerCase().replaceAll(" ", "-"); }
